### ISSUE TITLE
Guidelines for updating FW of BG96 refer to non-existing links

### ISSUE THREAD

**Issue by asvand** [1NCE-GmbH/blueprint-freertos#1]
Hi all,

the doc https://github.com/1NCE-GmbH/blueprint-freertos/blob/initial_release/Utilities/Modem_FW/How%20to%20flash%20BG96%20board.pdf refers to https://mega.nz/#!M3ADlbYA!0F8O9dJGxN9x6iIzbP37Q9YQiOuXZLH3HhO-mhfpS6A and https://mega.nz/#!124BwapY!3L9g1TISTWX-nVLgMxtKrcbCH__aQEUNwDnX8a_hGIE.

Can you provide the respective downloads via other channels?

**Comment by HDGoldi** [comment]
@asvand Please check the new merge request which is closing this issue: https://github.com/1NCE-GmbH/blueprint-freertos/pull/2

- Download the Quectel BG96 Window USB driver from this url: https://jan-sulaiman-1nce-public.s3-eu-central-1.amazonaws.com/connectivity-suite/Blueprints/Quectel_LTE%265G_Windows_USB_Driver_V2.1.zip
- Download the modem FW flasher tool (QFlash) from this url: https://jan-sulaiman-1nce-public.s3-eu-central-1.amazonaws.com/connectivity-suite/Blueprints/QFlash_V4.12.zip
