### ISSUE TITLE
Code is not building 

### ISSUE THREAD

**Issue by khuram11** [1NCE-GmbH/blueprint-freertos#5]
### Board type

STM32 P-L496G-CELL02

### Modem

. BG96 

### Describe the bug

after downloading the freertosblueprint and importing it to stm32cuubeide , firstly it didnot locate nce_iot_c_sdk.h. if I maually add them then it gives following errors,

D:/STM32/STM32CubeIDE_1.13.2/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.11.3.rel1.win32_1.1.1.202309131626/tools/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld.exe: D:/STM32/STM32CubeIDE_1.13.2/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.11.3.rel1.win32_1.1.1.202309131626/tools/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\libc.a(libc_a-gettimeofdayr.o): in function `_gettimeofday_r':
(.text._gettimeofday_r+0xe): warning: _gettimeofday is not implemented and will always fail
D:/STM32/STM32CubeIDE_1.13.2/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.11.3.rel1.win32_1.1.1.202309131626/tools/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld.exe: aws_demos.elf section `._user_heap_stack' will not fit in region `RAM'
D:/STM32/STM32CubeIDE_1.13.2/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.11.3.rel1.win32_1.1.1.202309131626/tools/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld.exe: region `RAM' overflowed by 680 bytes
collect2.exe: error: ld returned 1 exit status
make[1]: *** [makefile:112: aws_demos.elf] Error 1
make: *** [makefile:105: all] Error 2
"make all" terminated with exit code 2.  Build might be incomplete.

23:42:46 Build Failed. 5 errors, 79 warnings. (took 54s.377ms)

### Expected Behavior

It should have build cleanly since I didnot make any changes to the code.

### Current Behavior

Its not building cleanly and having 5 errors, and 79 warnings

**Comment by jamali005** [comment]
Hi @khuram11 

I apologize for the delayed response.

Previously, we supported only the STM32 [B-L475E-IOT01A](https://www.st.com/en/evaluation-tools/b-l475e-iot01a.html) board. However, I’m pleased to inform you that with our latest release, we now support the [STM32 P-L496G-CELL02](https://www.st.com/en/evaluation-tools/p-l496g-cell02.html) board. I recommend testing the provided code using Visual Studio Code (VSCode) for smoother integration with the P-L496G-CELL02

**Comment by jamali005** [comment]
I will now close this issue. If you encounter any further issues, please feel free to open a new one.
